// Permission constants matching backend API
export const PERMISSIONS = {
  // Patient permissions
  VIEW_PATIENT: 'VIEW_PATIENT',
  CREATE_PATIENT: 'CREATE_PATIENT',
  UPDATE_PATIENT: 'UPDATE_PATIENT',
  DELETE_PATIENT: 'DELETE_PATIENT',
  
  // Appointment permissions
  VIEW_APPOINTMENT: 'VIEW_APPOINTMENT',
  CREATE_APPOINTMENT: 'CREATE_APPOINTMENT',
  UPDATE_APPOINTMENT: 'UPDATE_APPOINTMENT',
  CANCEL_APPOINTMENT: 'CANCEL_APPOINTMENT',
  
  // Medical Record permissions
  VIEW_MEDICAL_RECORD: 'VIEW_MEDICAL_RECORD',
  CREATE_MEDICAL_RECORD: 'CREATE_MEDICAL_RECORD',
  UPDATE_MEDICAL_RECORD: 'UPDATE_MEDICAL_RECORD',
  
  // Prescription permissions
  VIEW_PRESCRIPTION: 'VIEW_PRESCRIPTION',
  CREATE_PRESCRIPTION: 'CREATE_PRESCRIPTION',
  UPDATE_PRESCRIPTION: 'UPDATE_PRESCRIPTION',
  
  // Lab permissions
  VIEW_LAB_RESULTS: 'VIEW_LAB_RESULTS',
  CREATE_LAB_ORDER: 'CREATE_LAB_ORDER',
  UPDATE_LAB_RESULTS: 'UPDATE_LAB_RESULTS',
  
  // Billing permissions
  VIEW_BILLING: 'VIEW_BILLING',
  CREATE_INVOICE: 'CREATE_INVOICE',
  PROCESS_PAYMENT: 'PROCESS_PAYMENT',
  
  // User Management permissions
  VIEW_USER: 'VIEW_USER',
  CREATE_USER: 'CREATE_USER',
  UPDATE_USER: 'UPDATE_USER',
  DEACTIVATE_USER: 'DEACTIVATE_USER',
  
  // Admin-specific permissions (request backend to add these)
  VIEW_ANALYTICS: 'VIEW_ANALYTICS',
  VIEW_SECURITY_LOGS: 'VIEW_SECURITY_LOGS',
  MANAGE_PERMISSIONS: 'MANAGE_PERMISSIONS',
  MANAGE_SETTINGS: 'MANAGE_SETTINGS',
} as const;

export type Permission = typeof PERMISSIONS[keyof typeof PERMISSIONS];
